---
title: "Shuang Liang's CV"
author:
  firstname: Shuang
  lastname: Liang
  address: "WeChat Official Account: Computational Social Science Research"
  position: TechFin・FinTech・RegTech
  contacts:
    - icon: fa phone
      text: "Phone: 133 4897 3380"
    - icon: fa envelope
      text: "Email: liangs2021@econ.pku.edu.cn"
      url: "mailto:liangs2021@econ.pku.edu.cn"
    - icon: fa globe
      text: "Personal Homepage: shuangliang1108.github.io"
      url: "https://shuangliang1108.github.io/"
format: awesomecv-typst
execute:
  echo: false
  warning: false
  message: false
brand:
  typography: 
    fonts:
      - family: Roboto
        source: google
        weight: [100, 400, 700]
      - family: Source Sans 3
        source: google
        weight: [100, 400, 700]
        style: [normal, italic]
    base: Source Sans 3
  color:
    primary: "#dc3522"
    link: "#771822"
  defaults: 
    awesomecv-typst:
      font-header: Roboto
---

```{r}
# install.packages("typstcv", repos = "https://kazuyanagimoto.r-universe.dev")
library(typstcv)
```


## Education

```{r}
#| output: asis
resume_entry(educ)
```


## Publications

```{r}
#| output: asis
resume_entry(pub)
```

## Work Experience

```{r}
#| output: asis
work |>
  format_date(end = "end", date_format = "%Y", sort_by = "start") |>
  resume_entry()
```

## Awards

```{r}
#| output: asis
resume_entry(award, details = c("detail1", "detail2"))
#resume_entry(award, details = grep("^detail", names(award)))
```

## Skills

```{r}
#| output: asis
resume_entry(skill)
```