proj1:
  title: Mechanisms and Pathways for Enhancing Production Resilience in Major Grain-Producing Areas under Extreme Climate Shocks
  location: Vertical Project
  date: 2025 - Present
  description: National Social Science Fund of China (General Program), Participant

proj2:
  title: The Industrialization Process and the Nationwide System in New China
  location: Vertical Project
  date: 2021 - Present
  description: Chinese Academy of Social Sciences, Major Marxist Theory Program, Participant

proj3:
  title: Reform Deepening and Upgrading of Supply and Marketing Cooperative-Owned Enterprises and Pathways for Fostering Leading Backbone Enterprises
  location: Vertical Project
  date: 2024 - 2025
  description: All China Federation of Supply and Marketing Cooperatives, Key Participant

proj4:
  title: Four Obstacles Facing Land Trust from the Perspectives of Farmers and the State: Evidence from Four Land Trust Projects
  location: Vertical Project
  date: 2014 - 2016
  description: National Undergraduate Innovation Experiment Program, Project Leader

proj5:
  title: Financial Support Models for “Three-Asset” Businesses and the Development of New Rural Collective Economies
  location: Horizontal Project
  date: 2025
  description: China Construction Bank, Key Participant

proj6:
  title: Credit Risk Evaluation System for Rural Collective Economic Organizations
  location: Horizontal Project
  date: 2024
  description: China Construction Bank, Key Participant